name: fcio-py

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
  release:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: Build & Test Compilation
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get dependencies and install fcio-py
      run: |
        python -m pip install --upgrade build
        make && make install

#  build-docs:
#    name: Build documentation
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - uses: actions/setup-python@v2
#        with:
#          python-version: '3.10'
#      - name: Setup build environment
#        run: |
#          python -m pip install --upgrade pip wheel setuptools
#          python -m pip install --upgrade .[docs]
#      - name: Build docs for current ref
#        run: |
#          cd docs
#          make clean
#          make
#